### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by lukestringer90**
I've added support for Swift Package Manager by making the following changes:

- Add Package.swift
- Move source files into a `/Sources` directory
- Rename example project to be consistent with other SPM projects
- Update some access modifiers to `public` so they can be accessed from other modules
    - @radianttap I have exposed the types and functions that I needed for my implementation, however I recommend you check I am not exposing things you want keep internal to the module. Also it might be that other things should be made public that I am unaware of. This is your call. 
- Add explanation of how to install using SPM to README

In merging this branch in you should also create a `1.1.0` tag as I specific this is the version in `Package.swift` (you are currently using `1.0`)

Finally - thanks for writing this code. I am using it in my app [Pivot](https://twitter.com/GetPivotApp) to render HTML to PDFs. It works great 👌

### CODE REVIEW

**Comment by radianttap** [comment]
I think I have one old project still using this, thanks for keeping it alive.

**Comment by lukestringer90** [comment]
Thanks for accepting @radianttap Could you also add the `1.1.0` tag so the right version can be resolved by SPM?

**Comment by guci0** [comment]
Maybe it's good time to some update to SwiftUI? And a little, as small as possible example? This "class", package is must have in a lot of application, but now I have problem to implement this... right.

**Comment by radianttap** [comment]
> Thanks for accepting @radianttap Could you also add the `1.1.0` tag so the right version can be resolved by SPM?

Added the tag. I am used to using master branch instead of version for SPM, way less administrative trouble.

**Pull request merged**
